// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Allowlisted metadata returned alongside an artifact payload chunk.
 */
export type ArtifactMetadata = { artifactId: string, threadId: string, artifactType: string, identityKey: string,
/**
 * Unix timestamp in seconds when the artifact was attached.
 */
createdAt: number, };
