// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an item is known to survive the next compaction.
 */
export type CompactionSurvival = "true" | "false" | "unknown";
