// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime build identity associated with a context snapshot.
 */
export type ContextRuntimeBuildInfo = { version: string, buildCommit: string, target: string, };
