// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects whether an inspection came from a live, speculative, or cold view.
 */
export type ContextSnapshotKind = "live" | "speculative" | "cold";
