// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audience visibility for an inspected item or group.
 */
export type ContextVisibility = "model" | "user" | "internal" | "unknown";
