// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextInspectionGroup } from "./ContextInspectionGroup";
import type { ContextInspectionItem } from "./ContextInspectionItem";
import type { ContextRuntimeBuildInfo } from "./ContextRuntimeBuildInfo";
import type { ContextSnapshotKind } from "./ContextSnapshotKind";

/**
 * Read-only projection of a model context and its provenance.
 */
export type ContextInspection = { threadId: string, turnId: string | null, snapshotKind: ContextSnapshotKind, partial: boolean, itemCount: number, estimatedPromptTokens: number | null, estimatedActiveTokens: number | null, estimatedContextWindowTokens: number | null, cachedInputTokens: number | null, uncachedInputTokens: number | null, cacheWriteInputTokens: number | null, runtimeBuildInfo: ContextRuntimeBuildInfo | null, configLayerRevision: string | null, runtimeFeatureRevision: string | null, persistedRuntimeBuildInfo: ContextRuntimeBuildInfo | null, persistedConfigLayerRevision: string | null, persistedRuntimeFeatureRevision: string | null, stale: boolean, windowId: string | null, contextWindowId: string | null, windowNumber: number | null, firstWindowId: string | null, previousWindowId: string | null, checkpointId: string | null, checkpointRevision: number | null, baseInstructions: ContextInspectionGroup, tools: ContextInspectionGroup, items: Array<ContextInspectionItem>, };
