// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactionSurvival } from "./CompactionSurvival";
import type { ContextLogicalOrigin } from "./ContextLogicalOrigin";
import type { ContextVisibility } from "./ContextVisibility";

/**
 * A prompt component accounted for outside the response-item list.
 */
export type ContextInspectionGroup = { index: number, itemCount: number, role: string, contentKind: string, logicalOrigin: ContextLogicalOrigin, visibility: ContextVisibility, estimatedTokens: number, serializedBytes: number, survivesCompaction: CompactionSurvival, encrypted: boolean, duplicateGroup: string | null, duplicateCount: number, preview: string | null, };
