// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Logical provenance for one model-visible item or prompt group.
 */
export type ContextLogicalOrigin = "baseInstructions" | "threadContext" | "turnContext" | "worldState" | "inheritedHistory" | "newOutput" | "toolOutput" | "compactionReplacement" | "derived" | "unknown";
