// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactionSurvival } from "./CompactionSurvival";
import type { ContextLogicalOrigin } from "./ContextLogicalOrigin";
import type { ContextVisibility } from "./ContextVisibility";

/**
 * One response item in the model-visible prompt.
 */
export type ContextInspectionItem = { index: number, role: string, contentKind: string, logicalOrigin: ContextLogicalOrigin, visibility: ContextVisibility, estimatedTokens: number, serializedBytes: number, survivesCompaction: CompactionSurvival, duplicateGroup: string | null, duplicateCount: number, encrypted: boolean, preview: string | null, };
