// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { EvidenceReference } from "./EvidenceReference";
import type { EvidenceStatus } from "./EvidenceStatus";

/**
 * Metadata-only receipt returned by the evidence APIs.
 */
export type Evidence = { receiptId: string, schemaVersion: bigint,
/**
 * Extension-defined kind. Unknown kinds are preserved verbatim.
 */
kind: string, subject: string, status: EvidenceStatus, threadId: string | null, turnId: string | null, jobId: string | null, planSnapshotId: string | null,
/**
 * Unix timestamp in seconds when the receipt was created.
 */
createdAt: number, source: string, provenance: JsonValue | null, tags: { [key in string]?: string }, refs: Array<EvidenceReference>,
/**
 * Bounded, redacted metadata supplied by the trusted host integration.
 */
metadata: JsonValue | null, };
