// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bounded reference to a canonical rollout item or artifact.
 */
export type EvidenceReference = { kind: string, id: string, };
