// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable status vocabulary for host-attached evidence.
 */
export type EvidenceStatus = "pass" | "fail" | "blocked" | "inconclusive" | "informational";
