// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetMemberState } from "./FleetMemberState";

/**
 * Result for one member during a fleet lifecycle operation.
 */
export type FleetResult = { operationId: string, memberId: string, threadId: string | null, runId: string | null, requestedState: FleetMemberState, previousState: FleetMemberState | null, finalState: FleetMemberState | null, success: boolean, error: string | null, depth: number, orderIndex: number, updatedAt: number, };
