// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetMemberState } from "./FleetMemberState";

/**
 * One member visible in a fleet status response.
 */
export type FleetMember = { memberId: string, threadId: string | null, runId: string | null, parentMemberId: string | null, state: FleetMemberState, depth: number, orderIndex: number, updatedAt: number, };
