// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime state of one member in an agent fleet.
 */
export type FleetMemberState = "running" | "waitingForTool" | "waitingForApproval" | "waitingForUser" | "idle" | "suspended" | "closed" | "failed";
