// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of the persisted full-text index used by thread listing and search.
 */
export type IndexState = "building" | "ready" | "unavailable" | "recoverable";
