// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStatus } from "./JobStatus";
import type { TerminalOutcome } from "./TerminalOutcome";
import type { ThreadClass } from "./ThreadClass";

/**
 * Durable lifecycle metadata for one transient job.
 *
 * This type intentionally has no stdout, stderr, tool output, or model
 * response field. Those bytes remain available through the rollout/artifact
 * references maintained by the workflow implementation.
 */
export type Job = {
/**
 * For transient jobs this is also the run and hidden thread identity.
 */
id: string,
/**
 * Classification of the persisted workflow run. Jobs always use
 * `transientJob`, but returning it makes cross-class projections explicit.
 */
threadClass: ThreadClass,
/**
 * Thread associated with this job's durable rollout.
 */
threadId: string,
/**
 * Root thread of the agent tree, when the job belongs to one.
 */
rootThreadId: string | null,
/**
 * Parent run, when the job was created as a delegated child.
 */
parentRunId: string | null, status: JobStatus,
/**
 * Terminal outcome, or `null` while the job is still running.
 */
outcome: TerminalOutcome | null,
/**
 * Client-supplied idempotency key, when one was supplied.
 */
idempotencyKey: string | null, modelProvider: string | null, model: string | null, cwd: string | null,
/**
 * Unix timestamp in seconds when the job was created.
 */
createdAt: number,
/**
 * Unix timestamp in seconds when the job was last updated.
 */
updatedAt: number,
/**
 * Unix timestamp in seconds when execution started.
 */
startedAt: number | null,
/**
 * Unix timestamp in seconds when execution finished.
 */
finishedAt: number | null,
/**
 * Optimistic-concurrency version of the workflow record.
 */
version: number, };
