// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current lifecycle state of a durable job.
 */
export type JobStatus = "pending" | "running" | "succeeded" | "failed" | "blocked" | "inconclusive" | "cancelled" | "aborted";
