// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanLifecycle } from "./PlanLifecycle";

export type PlanSummary = { id: string, title: string, path: string, threadId: string | null, turnId: string | null, cwd: string | null, model: string | null, createdAt: number, updatedAt: number, revision: number, lifecycle: PlanLifecycle, };
