// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal outcome recorded for a completed or stopped job.
 */
export type TerminalOutcome = "succeeded" | "failed" | "blocked" | "inconclusive" | "cancelled" | "aborted";
