// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes the immutable position at which a recovery preview was produced.
 *
 * The recovery token is valid only while the source rollout still ends at this
 * position. A later append invalidates the token and the create operation must
 * fail closed instead of attempting to recover from a moving history.
 */
export type ThreadRecoveryWatermark = {
/**
 * Rollout identity used by the recovery engine.
 */
rolloutId: string,
/**
 * Exclusive rollout item ordinal covered by the preview.
 */
endOrdinalExclusive: bigint,
/**
 * Exclusive byte offset covered by the preview.
 */
endByteOffset: bigint, };
