// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classification used by the workflow projections and thread filters.
 */
export type ThreadClass = "interactive" | "subAgent" | "transientJob" | "internal" | "legacyExec";
