// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One persisted item or turn that the recovery engine will omit.
 */
export type ThreadRecoveryExcludedItem = {
/**
 * Original immutable rollout ordinal.
 */
rolloutOrdinal: bigint,
/**
 * Stable item identity, when the invalid item has one.
 */
itemId: string | null,
/**
 * Turn identity, when the omitted entry represents a failed continuation.
 */
turnId: string | null,
/**
 * Bounded, provider-neutral explanation for the omission.
 */
reason: string, };
