// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts returned with a recovery preview.
 */
export type ThreadRecoveryCounts = { totalItems: bigint, retainedItems: bigint, excludedItems: bigint, failedTurns: bigint, };
