// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceLeaseMode } from "./WorkspaceLeaseMode";
import type { WorkspaceLeaseState } from "./WorkspaceLeaseState";

/**
 * Display-safe summary of one workspace lease.
 *
 * The normalized paths are display values only. Comparison keys, lease
 * tokens, and other fencing internals are never exposed by this type.
 */
export type WorkspaceLease = { leaseId: string, rootThreadId: string, ownerThreadId: string, normalizedPaths: Array<string>, mode: WorkspaceLeaseMode, state: WorkspaceLeaseState, generation: number, environmentId: string | null,
/**
 * Unix timestamp in seconds when the lease was issued.
 */
issuedAt: number,
/**
 * Unix timestamp in seconds when the lease expires, if bounded.
 */
expiresAt: number | null,
/**
 * Unix timestamp in seconds when the lease was explicitly released.
 */
releasedAt: number | null, };
