// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceLease } from "./WorkspaceLease";

/**
 * One newly granted lease and its fencing token.
 *
 * Tokens are returned only by `workspaceLease/grant`; they are not part of
 * [`WorkspaceLease`] and therefore cannot appear in list responses.
 */
export type WorkspaceLeaseGrant = { lease: WorkspaceLease, token: string, };
